services:
  python:
    image: genjiohara/python
    container_name: dockerfiles-python
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    tty: true
